/**
 * 全仓隐私 / 痕迹扫描（发布前必跑）：`npm run scan`。
 *
 * 两类都要扫，第二类最容易漏：
 *   ① 能定位到人的：邮箱、本机绝对路径、真实姓名、雇主/学校名；
 *   ② 能看出「这活儿怎么来的」的痕迹：AI 署名、生成器模板、私人称呼转述。
 *
 * ⚠️ 为什么「真实姓名 / 雇主名」不写在这个文件里：
 *   这个脚本会进公开仓库 —— 把要扫的词写在要公开的文件里，等于把敏感词
 *   本身发表了（脚本自己变成了泄漏源）。所以它们放在
 *   `local-data/privacy-words.txt`（整目录已被 .gitignore 排除），
 *   一行一个词，仓库里只有通用规则。
 *
 * ⚠️ 词表缺失时必须**大声说出来**：少了一份词表，扫描会静默变弱、还照样打勾，
 *   这种「看着扫过了」比不扫更坏。加 `--strict` 可以让它直接失败。
 *
 * 用法：
 *   node scripts/scan-privacy.mjs [目录，默认当前目录] [--strict]
 */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const args = process.argv.slice(2);
const strict = args.includes('--strict');
const ROOT = args.find((a) => !a.startsWith('--')) || '.';

/**
 * 扫描器自己必须跳过：模式定义里就写着 `Claude` / `WorkBuddy` 这些词，
 * 不跳的话每次都会在自己的第 44 行上报命中 —— 三条永久噪声，
 * 而这正是「报告里永远有几条红的、于是没人看报告」的开端。
 */
const SELF = fileURLToPath(import.meta.url);

/** 目录段名命中就跳过（按段比，不按前缀） */
const SKIP_SEG = new Set(['node_modules', '.git', 'dist', 'dist-electron', '.vite', 'local-data', '.tmp', 'coverage']);
const SKIP_EXT = new Set([
  '.png', '.jpg', '.jpeg', '.gif', '.webp', '.ico', '.bmp',
  '.zip', '.gz', '.7z', '.pdf',
  '.ttf', '.otf', '.woff', '.woff2',
  '.map', '.lock', '.exe', '.dll', '.node',
]);

/** 通用规则：任何项目都该为 0 */
const GENERIC = [
  [/[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}/, '邮箱'],
  [/[A-Za-z]:\\Users\\[^\\\s"']+/, '本机路径（Windows）'],
  // ⚠️ 必须排除盘符前缀：`C:/Users/work/…` 里也含 `/Users/`，
  // 不加这个 lookbehind，Windows 路径会被同时报成 macOS 路径（自己骗自己）。
  [/(?<![A-Za-z]:)\/Users\/[a-z0-9._-]+\//i, '本机路径（macOS）'],
  [/\/(?:home|Users)\/[a-z0-9._-]+\/(?:WorkBuddy|workbuddy)/, '本机工作区路径'],
  [/\bCo-Authored-By:/i, 'AI 署名（Co-Authored-By）'],
  [/\b(Generated with|Generated by) (Claude|ChatGPT|Copilot|CodeBuddy|WorkBuddy)\b/i, 'AI 署名（生成器）'],
  [/\b(Claude|ChatGPT|GPT-4|CodeBuddy|WorkBuddy)\b/, '模型 / 工具署名'],
];

function loadLocalWords() {
  const file = path.join(ROOT, 'local-data', 'privacy-words.txt');
  if (!fs.existsSync(file)) return { file, words: [], missing: true };
  const words = fs
    .readFileSync(file, 'utf8')
    .split(/\r?\n/)
    .map((l) => l.trim())
    .filter((l) => l && !l.startsWith('#'));
  return { file, words, missing: false };
}

const local = loadLocalWords();
// 名字类词也拼成一个正则，逐行匹配
const LOCAL_RE = local.words.length
  ? new RegExp(`(${local.words.map((w) => w.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')).join('|')})`)
  : null;

let hits = 0;
let scanned = 0;
const byLabel = new Map();

function walk(dir) {
  for (const name of fs.readdirSync(dir)) {
    const full = path.join(dir, name);
    const rel = path.relative(ROOT, full).split(path.sep).join('/');
    const segs = rel.split('/');
    if (segs.some((s) => SKIP_SEG.has(s))) continue;

    let st;
    try {
      st = fs.statSync(full);
    } catch {
      continue;
    }
    if (st.isDirectory()) {
      walk(full);
      continue;
    }
    if (SKIP_EXT.has(path.extname(name).toLowerCase())) continue;
    // 扫描器自己：模式里就写着那几个署名词，不跳会自匹配（见 SELF 的说明）
    if (path.resolve(full) === path.resolve(SELF)) continue;
    // vite 每次跑 build / preview 都会在根目录留下一个「把 node_modules 里的真实
    // 绝对路径内联进去」的临时配置文件（已被 .gitignore 排除）。不跳的话，
    // 每次扫描都会报一片本机路径 —— 全是自己的噪声，久了就没人看这个报告了。
    if (/\.timestamp-.*\.mjs$/i.test(name)) continue;
    if (st.size > 800_000) continue;

    let text;
    try {
      text = fs.readFileSync(full, 'utf8');
    } catch {
      continue;
    }
    // 二进制里塞了非法字节就别硬按文本扫
    if (text.includes('\u0000')) continue;

    scanned += 1;
    text.split(/\r?\n/).forEach((line, i) => {
      const report = (label) => {
        hits += 1;
        byLabel.set(label, (byLabel.get(label) ?? 0) + 1);
        console.log(`${label} | ${rel}:${i + 1} | ${line.trim().slice(0, 120)}`);
      };
      for (const [re, label] of GENERIC) {
        if (re.test(line)) report(label);
      }
      if (LOCAL_RE && LOCAL_RE.test(line)) report('本地词表命中');
    });
  }
}

walk(ROOT);

console.log('');
if (local.missing) {
  console.log(`⚠️ 没找到本地词表 ${path.relative(process.cwd(), local.file)} —— 只跑了通用规则，`);
  console.log('   真实姓名 / 雇主名这一类**没有被检查**。发布前请把词表补上（一行一个词）。');
} else {
  console.log(`本地词表：${local.words.length} 个词（${path.relative(process.cwd(), local.file)}）`);
}
if (hits) {
  console.log(`\n✗ 命中 ${hits} 处（扫了 ${scanned} 个文件）`);
  for (const [label, n] of byLabel) console.log(`   · ${label}：${n}`);
  console.log('   ⚠️ 命中要先分辨是不是真实数据本身（包版本号、番剧原文里的字形都属误报）。');
  process.exit(1);
}
console.log(`\n✓ 隐私扫描 0 命中（扫了 ${scanned} 个文件）`);
if (local.missing && strict) process.exit(3);
